### ISSUE TITLE
Add unpublished (private) Datasets to files indices

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/files-api#8]

**Comment by kburke** [comment]
Want to confirm a couple of things.

First, we are duplicating everything that goes into the "public" index into the "private" index also, as I understand is done for "entities" in search-api.  Or said another way, "public" is a subset of "private".

Second, files-api doesn't define any endpoint which deals with Elasticsearch index names, and therefore doesn't actually need a "virtual" name like search-api has for multiple "real" indices.  As shown in the image, I can keep the index names on non-hierarchical constants, internal to files-api, for the required operations.  I will still need to confirm search-api works with both during a call to hm_files/search.
![image](https://user-images.githubusercontent.com/209327/204910843-8ffcb957-1074-4148-b0d6-7804766e2324.png)
